services:
  db:
    image: postgres:17.4
    container_name: ruby-dev-test-db-raoni
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5437:5432" #Essa é sua porta local 5437, troque-a se necessário
    volumes:
      - ruby_dev_test_db_volume_raoni:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: ruby-dev-test-redis-raoni
    ports:
      - "6377:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruby-dev-test-web-raoni
    depends_on:
      - db
    ports:
      - "3007:3000"
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 12345678
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "rm tmp/pids/*.pid bundle install && bin/rails server -b 0.0.0.0 -p 3000"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ruby-dev-test-sidekiq-raoni
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 12345678
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
    working_dir: /app
    command: bundle exec sidekiq

volumes:
  ruby_dev_test_db_volume_raoni:

